name: Deploy Synapse (main)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write   # OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI version
        run: az version

      - name: Who am I
        run: az account show

      - name: Validate Bicep
        run: az deployment group validate \
              -g rg2 \
              --template-file main.bicep \
              --parameters params/main.test.bicepparam \
                           sqlAdminPassword='${{ secrets.SQL_ADMIN_PASSWORD }}'

      - name: Deploy
        run: az deployment group create \
              -g rg2 \
              --template-file main.bicep \
              --parameters params/main.test.bicepparam \
                           sqlAdminPassword='${{ secrets.SQL_ADMIN_PASSWORD }}'
